### PR TITLE
Text Colours

### PR DESCRIPTION
**Pull request by Richie-exe**
another one

### CODE REVIEW

**Comment by Dumbledore-web** [comment]
could you please explain what this fixes?

**Comment by Dumbledore-web** [comment]
there isn't any point adding code if it does nothing because it could break existing code

**Comment by Richie-exe** [comment]
when you click on a teacher's profile thing

**Comment by Dumbledore-web** [comment]
> when you click on a teacher's profile thing

image
here?

**Comment by Richie-exe** [comment]
ye

**Review by Dumbledore-web — APPROVED** [review]

**Pull request merged**
